package GUI;

import Account.Account;
import Library.Library;
import Models.User;
import Display.Popups;
import Models.Book;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

public class LibraryGUI extends javax.swing.JFrame {
    User c_user = new User();
    private String[][] bookTable;
    /**
     * Creates new form LibraryGUI
     */
    
    // gui initializer for testing (running this file directly)
    public LibraryGUI() {
        initComponents();
        c_user.setUserId(1);
        Account acct = new Account();
        Library lib = new Library();
        String[] name = acct.getAccountName(c_user);
        currentUser.setText("Welcome, " + name[0] + " " + name[1] + "!");
        initBookTable("");
        // Date and Time 
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateCurrentTime();
            }
        });
        timer.start();
        initButtons();
    }
    // gui initializer for actual use (to be access from Login.java
    public LibraryGUI(int id){
        initComponents();
        c_user.setUserId(id);
        Account acct = new Account();
        Library lib = new Library();
        String[] name = acct.getAccountName(c_user);
        currentUser.setText("Welcome, " + name[0] + " " + name[1] + "!");
        initBookTable("");
        // Date and Time 
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateCurrentTime();
            }
        });
        timer.start();
        // working on initButtons();
    }
    private void updateCurrentTime() {
        // Format the current date and time
        LocalDateTime currentDateTime = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String formattedDateTime = currentDateTime.format(formatter);

        // Update the text of the JLabel
        dateAndTime.setText(formattedDateTime);
    }
    public void initBookTable(String toSearch){
        Library lib = new Library();
        bookTable = lib.getBookListForTable(toSearch);
        tableOfBooks.setModel(new javax.swing.table.DefaultTableModel(
            bookTable,
            new String [] {
                "Book", "Author", "Genre", "Quantity", "Availability"
            }
        ));
        jScrollPane1.setViewportView(tableOfBooks);
    }
    public void initButtons(){
        // still in progress before implementation
        Library lib = new Library();
        
        if (lib.getBookGenres().length == 0){
            addBookButton.setEnabled(false);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        tableOfBooks = new javax.swing.JTable();
        refreshLibrary = new javax.swing.JButton();
        borrowBook = new javax.swing.JButton();
        appointmentsButton = new javax.swing.JButton();
        searchBook = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        editBookButton = new javax.swing.JButton();
        deleteBookButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addBookButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        recordsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        logOutButton = new javax.swing.JButton();
        currentUser = new javax.swing.JLabel();
        dateAndTime1 = new javax.swing.JLabel();
        dateAndTime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        accountMenu = new javax.swing.JMenu();
        changeName = new javax.swing.JMenuItem();
        changeEmail = new javax.swing.JMenuItem();
        changePassword = new javax.swing.JMenuItem();
        genreMenu = new javax.swing.JMenu();
        addGenre = new javax.swing.JMenuItem();
        deleteGenre = new javax.swing.JMenuItem();
        studentMenu = new javax.swing.JMenu();
        registerStudent = new javax.swing.JMenuItem();
        deleteStudent = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));

        tableOfBooks.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        tableOfBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Book", "Author", "Genre", "Quantity", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tableOfBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tableOfBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        if (tableOfBooks.getColumnModel().getColumnCount() > 0) {
            tableOfBooks.getColumnModel().getColumn(0).setResizable(false);
            tableOfBooks.getColumnModel().getColumn(1).setResizable(false);
            tableOfBooks.getColumnModel().getColumn(2).setResizable(false);
            tableOfBooks.getColumnModel().getColumn(3).setResizable(false);
            tableOfBooks.getColumnModel().getColumn(4).setResizable(false);
        }

        jScrollPane1.setViewportView(jPanel1);

        refreshLibrary.setBackground(new java.awt.Color(60, 110, 113));
        refreshLibrary.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        refreshLibrary.setForeground(new java.awt.Color(255, 255, 255));
        refreshLibrary.setText("Refresh");
        refreshLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshLibraryActionPerformed(evt);
            }
        });

        borrowBook.setBackground(new java.awt.Color(60, 110, 113));
        borrowBook.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        borrowBook.setForeground(new java.awt.Color(255, 255, 255));
        borrowBook.setText("Borrow Book");
        borrowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBookActionPerformed(evt);
            }
        });

        appointmentsButton.setBackground(new java.awt.Color(60, 110, 113));
        appointmentsButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        appointmentsButton.setForeground(new java.awt.Color(255, 255, 255));
        appointmentsButton.setText("Appointments");
        appointmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentsButtonActionPerformed(evt);
            }
        });

        searchBook.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N

        searchButton.setBackground(new java.awt.Color(60, 110, 113));
        searchButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        editBookButton.setBackground(new java.awt.Color(60, 110, 113));
        editBookButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        editBookButton.setForeground(new java.awt.Color(255, 255, 255));
        editBookButton.setText("Edit Book");
        editBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBookButtonActionPerformed(evt);
            }
        });

        deleteBookButton.setBackground(new java.awt.Color(60, 110, 113));
        deleteBookButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        deleteBookButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteBookButton.setText("Delete Book");
        deleteBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Library Operations:");

        addBookButton.setBackground(new java.awt.Color(60, 110, 113));
        addBookButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        addBookButton.setForeground(new java.awt.Color(255, 255, 255));
        addBookButton.setText("Add Book");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Miscellaneous:");

        recordsButton.setBackground(new java.awt.Color(60, 110, 113));
        recordsButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        recordsButton.setForeground(new java.awt.Color(255, 255, 255));
        recordsButton.setText("Records");
        recordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordsButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(60, 110, 113));

        logOutButton.setBackground(new java.awt.Color(60, 110, 113));
        logOutButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("Log Out");
        logOutButton.setBorderPainted(false);
        logOutButton.setContentAreaFilled(false);
        logOutButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logOutButtonMouseMoved(evt);
            }
        });
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutButtonMouseExited(evt);
            }
        });
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        currentUser.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        currentUser.setForeground(new java.awt.Color(255, 255, 255));
        currentUser.setText("Welcome, First Name Last Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(currentUser)
                .addGap(477, 477, 477)
                .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        dateAndTime1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        dateAndTime1.setForeground(new java.awt.Color(0, 0, 0));
        dateAndTime1.setText("Date & Time: ");

        dateAndTime.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        dateAndTime.setForeground(new java.awt.Color(0, 0, 0));
        dateAndTime.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(searchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateAndTime1)
                            .addComponent(dateAndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(borrowBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refreshLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editBookButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBookButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addBookButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(recordsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addComponent(appointmentsButton, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(55, 55, 55))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(searchBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appointmentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateAndTime1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateAndTime))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 559, Short.MAX_VALUE)))
        );

        accountMenu.setText("Account");
        accountMenu.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N

        changeName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        changeName.setText("Change Name");
        changeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNameActionPerformed(evt);
            }
        });
        accountMenu.add(changeName);

        changeEmail.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        changeEmail.setText("Change Email");
        changeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEmailActionPerformed(evt);
            }
        });
        accountMenu.add(changeEmail);

        changePassword.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        changePassword.setText("Change Password");
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });
        accountMenu.add(changePassword);

        jMenuBar1.add(accountMenu);

        genreMenu.setText("Genre");
        genreMenu.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N

        addGenre.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        addGenre.setText("Add Genre");
        addGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGenreActionPerformed(evt);
            }
        });
        genreMenu.add(addGenre);

        deleteGenre.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        deleteGenre.setText("Delete Genre");
        deleteGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGenreActionPerformed(evt);
            }
        });
        genreMenu.add(deleteGenre);

        jMenuBar1.add(genreMenu);

        studentMenu.setText("Student");
        studentMenu.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N

        registerStudent.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        registerStudent.setText("Register Student");
        registerStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerStudentActionPerformed(evt);
            }
        });
        studentMenu.add(registerStudent);

        deleteStudent.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        deleteStudent.setText("Delete Student");
        deleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentActionPerformed(evt);
            }
        });
        studentMenu.add(deleteStudent);

        jMenuBar1.add(studentMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGenreActionPerformed
        new AddGenre().setVisible(true);
    }//GEN-LAST:event_addGenreActionPerformed

    private void deleteGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGenreActionPerformed
        new DeleteGenre().setVisible(true);
    }//GEN-LAST:event_deleteGenreActionPerformed

    private void changeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNameActionPerformed
        new ChangeAcctName(c_user).setVisible(true);
    }//GEN-LAST:event_changeNameActionPerformed

    private void changeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEmailActionPerformed
        new ChangeAcctEmail(c_user).setVisible(true);
    }//GEN-LAST:event_changeEmailActionPerformed

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        new ChangeAcctPassword(c_user).setVisible(true);
    }//GEN-LAST:event_changePasswordActionPerformed

    private void registerStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerStudentActionPerformed
        new RegisterStudent().setVisible(true);
    }//GEN-LAST:event_registerStudentActionPerformed

    private void deleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentActionPerformed
        new DeleteStudent().setVisible(true);
    }//GEN-LAST:event_deleteStudentActionPerformed

    private void refreshLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshLibraryActionPerformed
        Account acct = new Account();
        String[] name = acct.getAccountName(c_user);
        currentUser.setText("Current Library Admin: " + name[0] + " " + name[1]);
        
        Library lib = new Library();
        searchBook.setText("");
        initBookTable("");
    }//GEN-LAST:event_refreshLibraryActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        Library lib = new Library();
        initBookTable(searchBook.getText());
    }//GEN-LAST:event_searchButtonActionPerformed

    private void borrowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowBookActionPerformed
        try {
            int index = tableOfBooks.getSelectedRow();
            if(index != -1){
                int bookId = Integer.parseInt(bookTable[index][5]);
                String book_name = bookTable[index][0] + " (" + bookTable[index][1] + ")";
                if (Integer.parseInt(bookTable[index][3]) > 0){
                    new BorrowBook(bookId, book_name).setVisible(true);
                } else {
                    Popups.bookNotAvailable();
                }
                
            } else {
                Popups.noSelectedBookTo("borrow");
            }
        } catch (Exception e){
            Popups.noSelectedBookTo("borrow");
        }
    }//GEN-LAST:event_borrowBookActionPerformed

    private void appointmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentsButtonActionPerformed
        super.dispose();
        new Appointments(c_user.getUserId()).setVisible(true);
    }//GEN-LAST:event_appointmentsButtonActionPerformed

    private void editBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBookButtonActionPerformed
        try {
            int index = tableOfBooks.getSelectedRow();
            new EditBook(Integer.parseInt(bookTable[index][5])).setVisible(true);
        } catch (Exception e){
            Popups.noSelectedBookTo("edit");
        }
    }//GEN-LAST:event_editBookButtonActionPerformed

    private void deleteBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookButtonActionPerformed
        try {
            int index = tableOfBooks.getSelectedRow();
            if(index != -1){
                if(Popups.confirmBookDelete() == 0){
                    Library lib = new Library();
                    Book book = new Book();
                    book.setBook_id(Integer.parseInt(bookTable[index][5]));
                    book.setTitle(bookTable[index][0]);
                    lib.deleteBook(book);
                    initBookTable("");
                }
            } else {
                Popups.noSelectedBookTo("delete");
            }
        } catch (Exception e){
            Popups.noSelectedBookTo("delete");
        }
    }//GEN-LAST:event_deleteBookButtonActionPerformed

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
        new AddBook().setVisible(true);
    }//GEN-LAST:event_addBookButtonActionPerformed

    private void recordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordsButtonActionPerformed
        super.dispose();
        new Records(c_user.getUserId()).setVisible(true);
    }//GEN-LAST:event_recordsButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        super.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void logOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseExited
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_logOutButtonMouseExited

    private void logOutButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseMoved
        logOutButton.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_logOutButtonMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu accountMenu;
    private javax.swing.JButton addBookButton;
    private javax.swing.JMenuItem addGenre;
    private javax.swing.JButton appointmentsButton;
    private javax.swing.JButton borrowBook;
    private javax.swing.JMenuItem changeEmail;
    private javax.swing.JMenuItem changeName;
    private javax.swing.JMenuItem changePassword;
    private javax.swing.JLabel currentUser;
    private javax.swing.JLabel dateAndTime;
    private javax.swing.JLabel dateAndTime1;
    private javax.swing.JButton deleteBookButton;
    private javax.swing.JMenuItem deleteGenre;
    private javax.swing.JMenuItem deleteStudent;
    private javax.swing.JButton editBookButton;
    private javax.swing.JMenu genreMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton recordsButton;
    private javax.swing.JButton refreshLibrary;
    private javax.swing.JMenuItem registerStudent;
    private javax.swing.JTextField searchBook;
    private javax.swing.JButton searchButton;
    private javax.swing.JMenu studentMenu;
    private javax.swing.JTable tableOfBooks;
    // End of variables declaration//GEN-END:variables
}
